// @ts-check

// ../wordbank 폴더 구조에서 사이드바 자동 생성
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wordbankSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
